-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 04:56:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`activador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activador` (
  `idactivador` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idactivador`),
  CONSTRAINT `idactivador`
    FOREIGN KEY (`idactivador`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`),
  CONSTRAINT `idadmin`
    FOREIGN KEY (`idadmin`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`antecedentes` (
  `idantecedentes` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `familiares` VARCHAR(600) NULL DEFAULT NULL,
  `personales` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`idantecedentes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  `idcomentario` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `idconsulta` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idconsulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnostico` (
  `iddiagnostico` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `comentario` VARCHAR(600) NULL DEFAULT NULL,
  `diag` VARCHAR(600) NULL DEFAULT NULL,
  `pronostico` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`iddiagnostico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`exploracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exploracion` (
  `idexploracion` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `comentario` VARCHAR(600) NULL DEFAULT NULL,
  `cintura` FLOAT NULL DEFAULT NULL,
  `temperatura` FLOAT NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `estatura` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idexploracion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratorio` (
  `idlaboratorio` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `colesterol` FLOAT NULL DEFAULT NULL,
  `trigliceridos` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idlaboratorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `idmedico` INT(11) NOT NULL,
  PRIMARY KEY (`idmedico`),
  CONSTRAINT `idmedico`
    FOREIGN KEY (`idmedico`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitoreoclinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitoreoclinico` (
  `idmonitoreoClinico` INT(11) NOT NULL,
  `monitoreoClinico_has_diagnostico_diagnostico_iddiagnostico` INT(11) NOT NULL,
  PRIMARY KEY (`idmonitoreoClinico`, `monitoreoClinico_has_diagnostico_diagnostico_iddiagnostico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitor_diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitor_diagnostico` (
  `monitoreoClinico_idmonitoreoClinico` INT(11) NOT NULL,
  `diagnostico_iddiagnostico` INT(11) NOT NULL,
  INDEX `fk_monitor_diagnostico_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  INDEX `fk_monitor_diagnostico_diagnostico1_idx` (`diagnostico_iddiagnostico` ASC) VISIBLE,
  CONSTRAINT `fk_monitor_diagnostico_diagnostico1`
    FOREIGN KEY (`diagnostico_iddiagnostico`)
    REFERENCES `mydb`.`diagnostico` (`iddiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_diagnostico_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoclinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nutriologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nutriologo` (
  `idnutriologo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnutriologo`),
  CONSTRAINT `idnutriologo`
    FOREIGN KEY (`idnutriologo`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `idpaciente` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `paciente_monitor_monitoreoClinico_idmonitoreoClinico` INT(11) NOT NULL,
  PRIMARY KEY (`idpaciente`, `paciente_monitor_monitoreoClinico_idmonitoreoClinico`),
  CONSTRAINT `idpaciente`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`paciente_monito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente_monito` (
  `paciente_idpaciente` INT(11) NOT NULL,
  `monitoreoClinico_idmonitoreoClinico` INT(11) NOT NULL,
  PRIMARY KEY (`paciente_idpaciente`, `monitoreoClinico_idmonitoreoClinico`),
  INDEX `fk_paciente_monito_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_monito_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoclinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_monito_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idpost` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `ID_CAT` INT(11) NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_cat_idx` (`ID_CAT` ASC) VISIBLE,
  CONSTRAINT `fk_cat`
    FOREIGN KEY (`ID_CAT`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sintomas` (
  `idsintomas` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `astenia` VARCHAR(600) NULL DEFAULT NULL,
  `adinamia` VARCHAR(600) NULL DEFAULT NULL,
  `anorexia` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`idsintomas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idpost` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `ID_CAT` INT(11) NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_cat_idx` (`ID_CAT` ASC) VISIBLE,
  CONSTRAINT `fk_cat`
    FOREIGN KEY (`ID_CAT`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  `idcomentario` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`post_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_comentario` (
  `post_idpost` INT NOT NULL,
  `post_categoria_idcategoria` INT NOT NULL,
  `comentario_idcomentario` INT NOT NULL,
  INDEX `fk_post_comentario_post1_idx` (`post_idpost` ASC, `post_categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_post_comentario_comentario1_idx` (`comentario_idcomentario` ASC) VISIBLE,
  CONSTRAINT `fk_post_comentario_post1`
    FOREIGN KEY (`post_idpost` , `post_categoria_idcategoria`)
    REFERENCES `mydb`.`post` (`idpost` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comentario_comentario1`
    FOREIGN KEY (`comentario_idcomentario`)
    REFERENCES `mydb`.`comentario` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_post` (
  `post_idpost` INT NOT NULL,
  `post_categoria_idcategoria` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  INDEX `fk_usuario_post_post1_idx` (`post_idpost` ASC, `post_categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_usuario_post_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_post_post1`
    FOREIGN KEY (`post_idpost` , `post_categoria_idcategoria`)
    REFERENCES `mydb`.`post` (`idpost` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_post_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exploracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exploracion` (
  `idexploracion` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `comentario` VARCHAR(600) NULL DEFAULT NULL,
  `cintura` FLOAT NULL DEFAULT NULL,
  `temperatura` FLOAT NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `estatura` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idexploracion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitor_explo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitor_explo` (
  `monitoreoClinico_idmonitoreoClinico` INT NOT NULL,
  `exploracion_idexploracion` INT NOT NULL,
  INDEX `fk_monitor_explo_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  INDEX `fk_monitor_explo_exploracion1_idx` (`exploracion_idexploracion` ASC) VISIBLE,
  CONSTRAINT `fk_monitor_explo_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoClinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_explo_exploracion1`
    FOREIGN KEY (`exploracion_idexploracion`)
    REFERENCES `mydb`.`exploracion` (`idexploracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`antecedentes` (
  `idantecedentes` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `familiares` VARCHAR(600) NULL DEFAULT NULL,
  `personales` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`idantecedentes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitor_antecendetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitor_antecendetes` (
  `antecedentes_idantecedentes` INT NOT NULL,
  `monitoreoClinico_idmonitoreoClinico` INT NOT NULL,
  INDEX `fk_monitor_antecendetes_antecedentes1_idx` (`antecedentes_idantecedentes` ASC) VISIBLE,
  INDEX `fk_monitor_antecendetes_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  CONSTRAINT `fk_monitor_antecendetes_antecedentes1`
    FOREIGN KEY (`antecedentes_idantecedentes`)
    REFERENCES `mydb`.`antecedentes` (`idantecedentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_antecendetes_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoClinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sintomas` (
  `idsintomas` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `astenia` VARCHAR(600) NULL DEFAULT NULL,
  `adinamia` VARCHAR(600) NULL DEFAULT NULL,
  `anorexia` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`idsintomas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitor_sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitor_sintomas` (
  `monitoreoClinico_idmonitoreoClinico` INT NOT NULL,
  `sintomas_idsintomas` INT NOT NULL,
  INDEX `fk_monitor_sintomas_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  INDEX `fk_monitor_sintomas_sintomas1_idx` (`sintomas_idsintomas` ASC) VISIBLE,
  CONSTRAINT `fk_monitor_sintomas_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoClinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_sintomas_sintomas1`
    FOREIGN KEY (`sintomas_idsintomas`)
    REFERENCES `mydb`.`sintomas` (`idsintomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratorio` (
  `idlaboratorio` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `colesterol` FLOAT NULL DEFAULT NULL,
  `trigliceridos` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idlaboratorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`monitor_lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitor_lab` (
  `monitoreoClinico_idmonitoreoClinico` INT NOT NULL,
  `laboratorio_idlaboratorio` INT NOT NULL,
  INDEX `fk_monitor_lab_monitoreoClinico1_idx` (`monitoreoClinico_idmonitoreoClinico` ASC) VISIBLE,
  INDEX `fk_monitor_lab_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_monitor_lab_monitoreoClinico1`
    FOREIGN KEY (`monitoreoClinico_idmonitoreoClinico`)
    REFERENCES `mydb`.`monitoreoClinico` (`idmonitoreoClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_lab_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `mydb`.`laboratorio` (`idlaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
